#!/usr/bin/env bash
#This script displays listening ports

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address		Foreign Address		State		PID/Program name"
netstat -tuln | awk '$1 == "tcp" "print $1"\t"$2\t"$3\t\t\t"$7"\t"$NF}'

netstat -uln | awk '$1 == "udp" {print $1"\t"$2"\t"$3"\t\t\t"$7"\t"$NF"'

echo "Activate UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags	Type	State	I-Node	PID/Program name	Path"
netstat -lx | awk '$1 == "unix" {print $1"\t"$2"\t"$3\t\t"$4"\t"$5"\t"$6"\t\t"$7}'

