#!/usr/bin/env bash
#This script performs actions based onsignals

handle_sigterm_sigquit() {
echo "Deleting PID file and terminating"
rm -f /var/run/myscript.pid
exit 0
}

handle_sigint(){
echo "Y U no love me?!"
}

handle_sigterm() {
echo "I hate the kill command"
}

trap handle_sigterm_sigquit SIGQUIT SIGTERM
trap handle_sigint SIGINT
trap handle_sigterm SIGTERM

echo $$ > /var/run/myscript.pid

while :
do
echo "To infinity and beyond"
sleep 1
done
