#!/usr/bin/env bash
#This script tells the story of the /etc/passwd file.

while IFS=":" read -r username x userid x groupid x userinfo homedir shell; do
    passcode=$(grep "^$username:" /etc/shadow | cut -d: -f2)
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $userinfo"
done < /etc/passwd
