#!/usr/bin/env bash
#This script writes numbers from 1 to 2o and different messages based on the iteration numbers

counter=1

while [ $counter -le 20 ]; do
case $counter in
4)
echo "$counter"
echo "bad luck from China"
;;
9)
echo "$counter"
echo "bad luck from Japan"
;;
17)
echo "$counter"
echo "bad luck from Italy"
;;
*)
echo "$counter"
;;
esac
((counter++))
done
