#!/usr/bin/env bash
#This script checks the existence, emptiness and thype of school file

if  [ -e school ]; then
	echo "school file exixts"

	if [ -s school ]; then
		echo "school is not empty"
	else
		echo "school is empty"
	fi

	if [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
