#!/usr/bin/env bash
#This script configures an Ubuntu server with the some requirements

sudo sed -i 's/^127.0.01.*$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' /etc/hosts
