#!/usr/bin/env bash
# Configure Nginx to run as the nginx user and listen on port 8080
apt-get update
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/www/html
service nginx restart
